server:
  port: 9912

eureka:
  client:
    service-url:
      defaultZone: http://0.0.0.0:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    ribbon:
      eureka:
        enabled: true
      soa-ebay:
        IsSecure: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      httpclient:
        ssl:
          use-insecure-trust-manager: true
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: soa-products
          uri: lb:http://soa-products
          predicates:
            - Path=/products/**
        - id: soa-ebay-decrease
          uri: lb:http://soa-products
          predicates:
            - Path=/price/decrease/{decreasePercent}
          filters:
            - RewritePath=/price/decrease/(?<decreasePercent>.*), /products/prices?percent=${decreasePercent}&priceOperation=DECREASE
        - id: soa-ebay-increase
          uri: lb:http://soa-products
          predicates:
            - Path=/price/increase/{increasePercent}
          filters:
            - RewritePath=/price/increase/(?<increasePercent>.*), /products/prices?percent=${increasePercent}&priceOperation=INCREASE
