version: "3.9"
services:
  products-ejb:
    build:
      context: products/soa-products-ejb
      dockerfile: wildfly/Dockerfile
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - soa

  products:
    container_name: products
    image: openjdk:21-oracle
    volumes:
      - ./products/soa-products/build/libs/soa-products-0.0.1-SNAPSHOT.jar:/products.jar
    command: [ "java", "-jar", "-Dspring.profiles.active=cloud", "products.jar" ]
    ports:
      - "1516:1516"
    networks:
      - soa

  ebay-mssql:
    container_name: ebay-mssql
    image: openjdk:21-oracle
    volumes:
      - ./soa-ebay/build/libs/ebay-0.0.1-SNAPSHOT.jar:/ebay.jar
    command: [ "/bin/sh", "-c", "sleep 30 && java -jar -Dspring.profiles.active=mssql ebay.jar" ]
    ports:
      - "1515:1515"
    networks:
      - soa

  ebay-psql:
    container_name: ebay-psql
    image: openjdk:21-oracle
    volumes:
      - ./soa-ebay/build/libs/ebay-0.0.1-SNAPSHOT.jar:/ebay.jar
    command: [ "/bin/sh", "-c", "sleep 30 && java -jar -Dspring.profiles.active=psql ebay.jar" ]
    ports:
      - "1514:1515"
    networks:
      - soa

  config-server:
    build: cloud/config-server
    container_name: config-server
    networks:
      - soa
    ports:
      - "8095:8095"

  eureka-server:
    build: cloud/eureka-server
    container_name: eureka-server
    depends_on:
      - config-server
    networks:
      - soa
    ports:
      - "8761:8761"

networks:
  soa:
    name: soa-network
    external: true
