openapi: 3.0.0
info:
  title: Ebay Operations API
  version: 1.0.0
servers:
  - url: /ebay

paths:
  /price/increase/{increasePercent}:
    post:
      summary: Increase the price of all products by a given percentage
      parameters:
        - $ref: 'parameters.yaml#/components/parameters/IncreasePercentParameter'
      responses:
        200:
          description: Prices increased successfully
        400:
          description: Invalid params provided (e.g. negative percent)
          content:
            application/json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/Error400ResponseTo'

  /price/decrease/{decreasePercent}:
    post:
      summary: Decrease the price of all products by a given percentage
      parameters:
        - $ref: 'parameters.yaml#/components/parameters/DecreasePercentParameter'
      responses:
        200:
          description: Prices decreased successfully
        400:
          description: Invalid params provided (e.g. negative percent)
          content:
            application/json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/Error400ResponseTo'

components:
  schemas:
    Error400ResponseTo:
      type: object
      required: [ message, timestamp ]
      properties:
        message:
          type: string
        timestamp:
          type: string
