version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: gadelsha
      POSTGRES_PASSWORD: gadelsha_chistai
    ports:
      - "5432:5432"
    networks:
      - soa-network

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - postgres
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres/products
      FLYWAY_USER: gadelsha
      FLYWAY_PASSWORD: gadelsha_chistai
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./migrations:/flyway/sql
    networks:
      - soa-network

networks:
    soa-network:
      driver: bridge
      name: soa-network
