server:
    port: 8095
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nightness333/soa-ebay-config
          default-label: main
          clone-on-start: true
