openapi: 3.0.0
info:
  title: Ebay Operations API
  version: 1.0.0

tags:
  - name: prices

servers:
  - url: /api

paths:
  /price/increase/{increasePercent}:
    post:
      operationId: increasePrices
      tags:
        - prices
      summary: Increase the price of all products by a given percentage
      parameters:
        - $ref: 'parameters.yaml#/components/parameters/IncreasePercentParameter'
      responses:
        200:
          description: Prices increased successfully
        400:
          description: Invalid params provided (e.g. negative percent)
          content:
            application/json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/ApiErrorTo'

  /price/decrease/{decreasePercent}:
    post:
      operationId: decreasePrices
      tags:
        - prices
      summary: Decrease the price of all products by a given percentage
      parameters:
        - $ref: 'parameters.yaml#/components/parameters/DecreasePercentParameter'
      responses:
        200:
          description: Prices decreased successfully
        400:
          description: Invalid params provided (e.g. negative percent)
          content:
            application/json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/ApiErrorTo'
