version: "3.9"
services:
  products:
    container_name: products
    image: openjdk:21-oracle
    volumes:
      - ./soa-products/build/libs/products-0.0.1-SNAPSHOT.jar:/products.jar
    command: [ "java", "-jar", "-Dspring.profiles.active=cloud", "products.jar" ]
    ports:
      - "1516:1516"
    networks:
      - soa

  ebay:
    container_name: ebay
    image: openjdk:21-oracle
    volumes:
      - ./soa-ebay/build/libs/ebay-0.0.1-SNAPSHOT.jar:/ebay.jar
    command: [ "java", "-jar", "-Dspring.profiles.active=mssql,cloud", "ebay.jar" ]
    ports:
      - "1515:1515"
    networks:
      - soa

networks:
  soa:
    name: soa-network
    external: true
